### ISSUE TITLE
October 2021 Update

### ISSUE THREAD

**Issue by Adrian-Ng** [Adrian-Ng/cv#3]
Time to update the cv!

This CV has been doing ok. It gets a lot of attention from recruiters. But the type of job descriptions cover a big spread:

- data engineering 
- data analysis
- data quality
- data steward

Let's ensure the CV attracts job descriptions specific to my technical interests. So we might want to remove bits and bobs on data management, data quality analysis (focus on the engineering of the DQ tools).

Let's also make sure we cover graph, flight data. and perhaps mention being a SQL skills champion.

Next year, hopefully we can add:

- spark
- snowflake
- gdp bits and bobs

**Comment by oliviathompson** [comment]
You were a brilliant teacher of data science concepts too, would it be worth including that as experience?

**Comment by Adrian-Ng** [comment]
> You were a brilliant teacher of data science concepts too, would it be worth including that as experience?

o thank you! That might be worth including. Do you remember what topics we covered?
